# Travis CI config file
# https://docs.travis-ci.com/

dist: trusty

language: node_js

node_js:
  - "11.*"
  - "10.*"
  - "9.*"
  - "8.*"

cache:
  yarn: true

install:
  - yarn

before_script:
  - yarn build

script:
  - node test/_node-version-test.js
  - yarn test
